woowa-techcamp-2020/todo-1

src/app.js
src/index.html
src/javascripts/Components/Column.js
src/javascripts/Components/Element.js
src/javascripts/Components/Header.js
src/javascripts/Components/Hover.js
src/javascripts/Components/Kanban.js
src/javascripts/Components/KanbanPage.js
src/javascripts/Components/Note.js
src/stylesheets/kanban.css
src/stylesheets/style.css

> 칸반 페이지 렌더링 및 노트 드래그 기능 추가
- #3 
- #13 
- #16 
SPA 내부 컴포넌트 구현을 위해, 컴포넌트를 class형으로 선언해 사용
내부 dom을 rendering 하고 싶은 경우 render() 메소드를 호출하면 dom element를 return함
노트 드래그의 경우 drag&drop api를 사용한 것이 아닌 mouse event로 처리함
드래그 시 예외상황 처리 (에러)
- 마우스가 화면을 벗어 났을 때 : 드래그가 끝났을 떄와 같게 동작함
노트 드래그시 연관된 column의 내부 Array의 정보 수정
Array의 정보 수정시 왼쪽 상단 count도 변경

PR: 추가 - 칸반보드 페이지 마크업

---

apis/constants/config.js
apis/constants/message.js
apis/index.js
apis/login.js
apis/users.js
app.js
dao/DataAccessObject.js
dao/constants/config.js
dao/constants/poolOptions.js
dao/dao.js
dao/dto/User.js
dao/dto/UserToken.js
package.json

> DAO에 유저 토큰 발급하는 함수 추가,  이외 API에 필요한 전반적인 작업 진행함.
- #23 
- 앞으로 apis/index.js가 API에 대한 라우팅을 일괄 처리
- API 라우팅에 대한 정보는 일괄 확인할 수 있음
- 앞으로 API에서 보내는 상태 코드, 메세지는 이 곳에서 통합 관리하여, 유지보수를 고려.

PR: 추가 - 유저 액세스 토큰 API

---

src/javascripts/Components/ActivityLog.js
src/javascripts/Components/Header.js
src/javascripts/Components/KanbanPage.js
src/javascripts/Components/Log.js
src/stylesheets/activityLog.css

> 칸반 페이지에 액티비티 로그 컴포넌트를 추가함
- #3 
- #28 (mock 함수만 만들어놓음)
- #29 
칸반 페이지에 위치한 이유는 칸반 페이지가 header를 가지고 있기 때문에, 액티비티 로그 컴포넌트를 칸반 페이지에 적용함
header의 메뉴 버튼을 눌러야 액티비티 로그가 나와야 함.
액티비티 로그에는 시작시 데이터를 받아오는 내용과, 페이지네이션 기능을 API 통신 없이 간단하게 구현함
로그 컴포넌트를 구분하기 위해 액티비티 로그 창과 로그에 대한 컴포넌트를 분리함.
각 로그에 들어가는 데이터의 형태는 다음과 같다
```json
{
"user": "@유저네임",
"noteTitle": "해당노트제목",
"method": "로그작업타입",
"columnFrom": "발생한컬럼",
"columnTo": "이동한경우컬럼",
"time": "시간"
};
```

PR: 추가 - 액티비티 로그

---

src/javascripts/Components/Kanban.js

> 정상적인 동작만 가능하도록, 마우스 왼쪽클릭 (터치) 로만 동작하도록 설정
- #40
마우스 오른쪽 버튼을 누르는 경우, mousedown 이벤트는 발생하지만 mouseup 이벤트의 경우 제대로 동작하지 않는 버그가 존재함
따라서 mousedown 이벤트 핸들러에 safe guard를 추가함

[#40] fix: 추가 - 마우스 왼쪽 버튼으로만 동작

---

src/javascripts/Components/Column.js
src/javascripts/Components/Hover.js
src/javascripts/Components/Kanban.js
src/stylesheets/kanban.css

> 칸반 페이지 event handler 버그 수정 & 사용자 입장에서 기능 추가
- #3 
- #18 
- #26
노트 드래그 시, 이동할 다른 노트에 닿지 않고 컬럼 내에 위치만 하면 노트를 이동하도록 설정
더블클릭으로 모달을 띄우기 위해 더블클릭 핸들러 설정
마우스가 브라우저를 떠낫을 때 clicked를 false로 바꾸는 코드가 누락됨을 확인.
이를 고침
이를 그대로 둘 경우 mousemove 이벤트 핸들러가 계속 동작해 (clicked로 safe guard를 생성한 구조임) 에러가 발생함

PR: 추가 - 칸반페이지 event handler 버그 수정, 노트이동 기능 추가

---

apis/constants/message.js
apis/index.js
apis/kanban.js
dao/DataAccessObject.js
dao/DataAccessObject.spec.js
dao/dto/Column.js
dao/dto/Kanban.js
dao/dto/Note.js
dao/method/getKanbanData.js

> GET 요청으로 kanban id를 받으면 해당 칸반보드의 데이터를 가공해 return 하는 api
- #22 
URL 경로 : /api/get/:kanban_id
SQL로 받아온 rows를 가공할 때 사용할 DTO class들 생성함
- 칸반
- 컬럼
- 노트
인자로 받은 kanban_id와 연관된 note들을 전부 가져오되, column 정보와 함께 join 해서 가져옴.
이 때 column의 순서는 order로 관리하므로, ORDER BY를 사용함
DAO의 method로 직접 작성할 경우 DAO가 비대해지는 문제가 있어, getKanbanData를 메소드로 따로 작성하고, prototype으로 선언해 사용함
bind(this)를 이용해 내부 method에서 처리하려 했으나 제대로 동작하지않는 문제가 있어 prototype 사용
받아온 rows를 column별로, note별로 가공 작업을 진행
DTO로 전송할 때 가공된 데이터를 전송하기 위해 method에서 가공을 처리함
가공 작업 시, Map 객체를 이용해 logN으로 탐색을 진행해 속도를 향상함. 따라서 가공의 최종 시간 복잡도는 N + NlogN

PR: 추가 - 칸반 데이터를 가져오는 API

---

src/javascripts/Components/Column.js
src/javascripts/Components/Kanban.js
src/javascripts/Components/KanbanPage.js
src/javascripts/Components/Note.js

> 칸반보드 페이지에서 칸반 데이터를 API에서 요청해 사용하도록 설정
- #3
- #22 
작성한 API들에 맞추어 class들의 key 값을 수정함
기존 hard coding 되어있던 코드를 제거하고 API 에서 data를 fetch해서 가져 오도록 수정
fetching 작업은 비동기로 진행되지만, 이후에 앞서 결과를 사용하지 않아도 되므로 async 함수로 작성하지 않음

PR: 추가 - kanban 페이지 데이터 fetching

---

apis/constants/message.js
apis/kanban.js
dao/DataAccessObject.js
dao/DataAccessObject.spec.js
dao/dto/Note.js
dao/method/createNote.js

> columnId와 노트 정보를 입력받아 해당 column 맨 앞에 새 노트를 추가하는 API 제작
- #14
!!트랜잭션을 사용하기 위해 모듈을 mysql2/promise로 변경함
새로운 노트를 생성하는 DAO method 추가
순서는 다음과 같음
- 칼럼의 맨 앞에 있는 노트의 id를 가져옴
- 그 노트 앞에 새로운 노트를 추가함 (이전에 받은 id값으로 연결구조 생성)
- 이전에 맨 앞에 있던 노트의 연결구조를 update함
테스트 코드의 pool을 끝내는 endPool을 맨 afterAll에 따로 할당. 
이는 endPool을 맨 마지막에 실행하기 위함

PR: 추가 - 노트 추가 API

---

src/javascripts/Components/Column.js

>  노트 추가시 DB에도 저장하는 API 적용
- #9
- #14
column의 노트추가 버튼에 fetch 요청 추가
fetch 후 응답받은 response의 data로 넘어온 새로운 노트로 새 노트 생성
response의 success여부로 노트 추가 결정.
만약 실패인 경우 front view 에 노트 추가되지 않음

PR: 추가 - 노트 추가시 DB에도 저장

---

apis/constants/message.js
apis/kanban.js
dao/DataAccessObject.js
dao/DataAccessObject.spec.js
dao/method/createNote.js
dao/method/updateNote.js

> 노트의 내용을 수정하는 API 제작
- #17
- #14 (변수명 변경)
노트의 수정을 수행할 때 오류가 발생하는 경우를 대비해 transaction을 이용함
transaction의 경우 CRUD에서 R을 제외한 CUD에서 사용하려함.
이는 데이터의 변경 시 문제가 생겼을 때 유연하게 대처하기 위함

PR: 추가 - 노트 내용 수정 API

---

apis/constants/message.js
apis/kanban.js
dao/DataAccessObject.js
dao/DataAccessObject.spec.js
dao/method/deleteNote.js

> 노트를 삭제하는 API 추가
- #15 
연결 구조를 갱신해야 하기 때문에 순서는 다음과 같음
- 삭제하려는 노트의 연결 구조를 찾아옴
- prev 연결 구조 갱신
- next 연결 구조 갱신
- 해당 노트 삭제
노트를 삭제하는 메소드에 대한 테스트 코드를 추가함. 이전 테스트 코드에서 생성한 노트를 삭제하도록 구현함

PR: 추가 - 노트 삭제 API

---

apis/constants/message.js
apis/kanban.js
dao/DataAccessObject.js
dao/DataAccessObject.spec.js
dao/method/moveNote.js

> 노트의 연결관계를 변경시키는 API 추가
- #53 
현재 노트의 id와 이동할 위치의 앞, 뒤 노트의 id를 인자로 받아 순서를 바꿔주는 method 작성
1. 이전 노트와의 연결 관계를 끊어줌
2. 새 위치에 연관되어있는 노트들의 연결관계 갱신
노트 이동 시, 도착한 위치의 연결 관계가 유효한지 검사하는 safe guard 추가
테스트 항목
- 맨 끝으로 이동이 제대로 되는지
- 맨 처음으로 이동이 제대로 되는지
- 유효하지 않은 메소드 호출

PR: 추가 - 노트 이동 API

---

src/javascripts/Components/Column.js
src/javascripts/Components/Note.js

> 노트 수정, 삭제 이벤트 적용
- #10 
- #11
- 콜백 함수에서 이를 소유한 컬럼으로 접근하기 위해, 콜백 함수에 바인딩 걸어줌
- 노트 내용 수정될 때, 컬럼 내 데이터와 노트의 돔 데이터 함께 수정됨
(이전 내용과 동일하면, 수정 이벤트는 일어나지 않음)
- 노트 삭제 이벤트 처리

PR: 추가 - 노트 수정, 삭제 이벤트 적용

---

src/javascripts/Components/Column.js
src/javascripts/Components/Note.js

> 드래그 후 수정된 노트가 화면에 적용 안 되는 버그 해결
- #64 
다시 노트ID로 해당 DOM을 찾아서 지정해줌

PR: !HOTFIX - 드래그 후 수정된 노트가 화면에 적용 안 되는 버그

---

dao/method/functions/checkCorrectLink.js
dao/method/functions/pickNoteLink.js
dao/method/functions/pushNoteToEmptyColumn.js
dao/method/functions/updateNoteLink.js
dao/method/moveNote.js

> 노트를 드래그 후 원래 위치로 이동하는 경우에 대한 safe guard 추가
- #66
기존 로직의 경우 이동할 위치의 연결구조가 명확한지 판단을 먼저하고 DB에 이동 내용을 갱신함
원래 위치로 이동하는 경우 이동할 위치의 연결 구조를 계산하는 데 오류가 존재함.
이 로직의 순서를 이동하는 노트의 연결 구조를 끊은 뒤 검사하는 것으로 변경함
DAO의 해당 메소드의 양이 너무 많고, 보기 어려워 내부 함수로 이를 쪼갬

PR: !HOTFIX 노트 이동 dao method

---

src/javascripts/Components/Column.js
src/javascripts/Components/Kanban.js

> 객체 프로퍼티와 중복되는 데이터 제거
- #67
1. 객체 프로퍼티로 사용하도록 리팩토링
- 객체 프로퍼티와 중복해서 지닌 데이터때문에 데이터 변동 시,
일관되게 데이터를 모두 바꾸는 어려움이 있음

PR: refactor - 객체 프로퍼티와 중복되는 데이터 제거

---

src/javascripts/Components/Column.js
src/javascripts/Store/Store.js

> 유저 권한을 확인 추가 (수정, 삭제)
- #71
임시로 Store에 칸반에 대한 유저들 퍼미션 정보랑 유저 정보를 저장하도록 함
차후, 로그인 때 퍼미션 정보를 가져와, 유저 정보와 함께 저장할 것
(이름, 퍼미션 정보)

PR: feat - 유저 권한 확인

---

app.js
routes/spa.js
src/app.js
src/javascripts/Components/Element.js
src/javascripts/Components/ErrorPage.js
src/javascripts/Components/KanbanPage.js
src/javascripts/Components/LoginPage.js
src/javascripts/Components/Router.js
src/javascripts/Store/Store.js
src/stylesheets/error.css

> 페이지 라우팅을 위한 작업
- #71
- setPage 함수로 pageId와 pageComponent를 따로 등록해두고, 여러 Path에서
재사용 할 수 있도록 함
- 브라우저 reload 없이 화면을 그리기 위함.
- setErrorPage로 설정, Symbol로 생성된 ID로 씀으로써 사용자가 추가한 패턴에
중복되지 않도록 함.
- 현재, KanbanPage 객체가 갖고 있는 문제를 해결하기 위함
- runWhenRender 함수를 갖고 있으면, render 함수 실행 때, 실행하는 구조

PR: feat - 페이지 라우팅

---

apis/index.js
apis/kanban.js
apis/log.js
dao/DataAccessObject.js
dao/constants/log.js
dao/dto/Log.js
dao/method/createLog.js
dao/method/readLogs.js
src/javascripts/Components/ActivityLog.js
src/javascripts/Components/Column.js
src/javascripts/Components/Kanban.js
src/javascripts/Components/Log.js

> 액티비티 로그를 database에서 받아오는 기능 추가
- #8 
- #32 
- #27 
액티비티 로그를 생성하는 로직 추가
database schema 구조를 변경하는 이유
- noteId 등을 외래키로 설정하거나, 그렇게 title을 받아오는 경우, 이후에 내용이 바뀌었을 때, 이전 기록의 내용들도 title이 전부 바뀜
- 따라서 log가 생성될 때의 기록만 나타내도록 구성
액티비티 로그의 데이터를 서버에서 받아오도록 수정
Log 컴포넌트의 인자의 이름을 API로 받아온 데이터와 맞춤
페이지네이션은 offset과 limit으로 구현함

PR: 추가 - activity log 적용

---

apis/constants/config.js
apis/constants/message.js
apis/login.js
dao/dto/UserToken.js
src/app.js
src/javascripts/Components/KanbanPage.js
src/javascripts/Utils/cookie.js

> 토큰 쿠키로 유저 정보를 연동하고, 미로그인 시 로그인 페이지로 이동시킴
- #79
- #23
- cookie에 설정된 토큰 정보로 유저 정보를 반환함
- 쿠키 설정 부분에서 millisecond 가 아닌 second 단위로 설정돼있어,
쿠키가 매번 지워지던 버그 해결
- 미로그인 시, 로그인 페이지로 이동
- 요청 여부를 저장해둠으로써, 칸반 페이지 로드 시, 매번 이동시키던 문제 해결
- 만약 토큰 오류 시, 메세지와 함께 로그인 페이지로 이동됨

PR: feat - 토큰으로 유저 정보 연동 및 로그인 여부 확인

---

webpack.config.js

> 저번 데모 때 임시로 사용했던 웹팩 설정 되돌림
- #38
- fe1833787ec7987f281424553372eaa8712c9e00
없어진 엔트리 포인트로 인한 빌드 오류 해결

PR: fix - Webpack Entry Point / Plugin SPA 적용

---

src/app.js

>  파일 명을 일치시키기 위해 Loginpage를 LoginPage로 수정함
front 페이지의 entrypoint에서 LoginPage를 import 할 때, 대소문자에 오타 확인
local에서 작업할 때 제대로 동작하지만, 배포 페이지에서 제대로 동작하지 않는 오류를 발견
따라서 이를 수정함

PR: HOTFIX - import loginpage 파일 오타 수정

---

src/stylesheets/kanban.css

> column에 카드가 많은 경우 스크롤 가능하도록
- #3
기존에 ul에 overflow 속성으로 스크롤을 제작하려 했으나, ul 태그에 입력
overflow 속성에 제대로 동작하지 않음
따라서 이를 column로 위치를 옮김

PR: fix - 노트가 많은 경우 scroll

---

src/stylesheets/kanban.css

> 컬럼에 노트가 많은 경우 ul 태그에 overflow 속성 추가
- #85 
column에 직접 overflow를 설정하는 경우, 웹의 가로사이즈가 작아졌을 때 컬럼의 width도 줄어드는 문제가 있어, ul에 이를 지정함
ul에 height를 넣고 overflow를 설정하도록 수정
li에 height:inherit 부분 삭제

PR: fix - 컬럼에 노트가 많을 경우 overflow 속성 변경
